# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cbaccf6a88ec2b85cf34adf0a8f397f1b494997ccf3e0ec484265e59befc85ff157e54bce717af29ad0672795f9a59efe7d2cd8e93b5f45f057ad785dd4426de

test:
  secret_key_base: 22e2655dd841cd3262d60237e8b2d0ccf42d9d597018e43f926400010a965ff25d21309a9b8bc9a247979299e4fbee079e42a2efa2b94f15f73c2d527472eb51

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
